services:
  kosync:
    image: jacosverksted/koreader-sync-dashboard:latest
    container_name: kosync-dashboard
    restart: unless-stopped
    ports:
      - 7200:7200
    environment:
      - ENABLE_USER_REGISTRATION=true
      # - ADMIN_USERNAME=admin
      # - ADMIN_PASSWORD=your-secret-here
    volumes:
      - ./logs/app:/app/koreader-sync-server/logs
      - ./logs/redis:/var/log/redis
      - ./data/redis:/var/lib/redis
